
server:
  error:
    include-stacktrace: always
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/mainCorp-DB?createDatabaseIfNotExist=true
    username: root
    password: password123
  graphql:
    cors:
      allowed-origins: http://localhost:3000/
#  security:
#    user:
#      name: farai
#      password: farai
#security:
#  basic:
#    enabled: false


