
server:
  error:
    include-stacktrace: always
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/mainCorp-DB?createDatabaseIfNotExist=true
    username: root
    password: password123
  graphql:
    cors:
      allowed-origins: http://localhost:3000/

  mail:
    host: smtp.gmail.com
    port: 587
    username: bookinghaircut@gmail.com
    password: fnbqdcdjxurpumlj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB